statusbar: false
menubar: false
toolbar:
  - bold
  - italic
  - link
  - bullist
  - numlist
  - table
plugins:
  - table
  - autoresize
  - link
target_list: false 
autoresize_min_height: 130
extended_valid_elements : "iframe[max-height= 400px|tooltip] , a[href|target=_blank]"